- source/classes/InteractionWrapper.js
- source/classes/index.js
- source/commands/_commandDictionary.js
- source/commands/commands.js
- source/scripts/updateWiki.js
- wiki/Commands.md
Summary
-------
- added /commands
- removed CommandSet (now unused) 
- adjusted updateWiki to include permission info
Issue
-----
Closes #11
> #11: Port /commands

- source/classes/InteractionWrapper.js
- source/commands/_commandDictionary.js
- source/commands/about.js
Summary
-------
- port /about
Issue
-----
Closes #10
> #10: port /about

- source/classes/InteractionWrapper.js
- source/commands/bounty.js
- source/commands/stats.js
- source/commands/toast.js
- source/commands/version.js
- source/helpers.js
- source/modals/bountyeditmodal.js
- source/modals/bountypostmodal.js
- source/models/bounties/Bounty.js
Summary
-------
- added /bounty add-completers
- functionized extractUserIdsFromMentionString
- bounty posting and editing now removes select on errors
- choice arrays in CommandWrapper are now optional
- added Completers field to bounty embed
Issue
-----
Closes #5
> #5: added `/bounty add-completers`

- source/commands/bounty.js
Summary
-------
- Port `/remove-completer` as `/bounty remove-completer`
Issue
-----
Closes #6
> #6: Port `/remove-completer` as `/bounty remove-completer`

- source/commands/bounty.js
- source/commands/toast.js
- source/helpers.js
- source/models/bounties/Bounty.js
- source/models/users/Hunter.js
Summary
-------
- port `/complete` as `/bounty complete` flow
Issue
-----
Closes #7
> #7: Port `/complete` as `/bounty complete`

- source/commands/_commandDictionary.js
- source/commands/event.js
- source/commands/toast.js
Summary
-------
- added /event command
Issue
-----
Closes #1
> #1: add `/event` command

- source/commands/_commandDictionary.js
- source/commands/bounty.js
- source/commands/event.js
- source/commands/moderation.js
- source/selects/_selectDictionary.js
- source/selects/modtakedown.js
Summary
-------
- added `/moderation take-down`
- make "no open bounties" error in `/bounty edit` ephemeral
Issue
-----
Closes #46
> #46: added `/moderation take-down`

- source/commands/_commandDictionary.js
- source/commands/rank.js
- source/embedHelpers.js
- source/models/guilds/GuildRank.js
Summary
-------
- adds `/rank add` command
Issue
-----
Closes #20
> #20: add `/rank add`

- source/commands/rank.js
Summary
-------
- add `/rank remove`
Issue
-----
Closes #22
> #22: add `/rank remove`

- README.md
- source/commands/bounty.js
- source/commands/event.js
- source/selects/_selectDictionary.js
- source/selects/bountyswapbounty.js
- source/selects/bountyswapslot.js
Summary
-------
- add `/bounty swap`
Issue
-----
Closes #32
> #32: add `/bounty swap`

- package-lock.json
- package.json
- source/bot.js
- source/scripts/clearCommands.js
- source/scripts/uploadCommandsToTestGuild.js
Summary
-------
- updated discord.js to v14.12.1
- removed `discord-api-types` from dependencies, as `discord.js` includes it for its own use
Issue
-----
Closes #54
> #54: Update discord.js to v14.12.1

- source/commands/moderation.js
Summary
-------
- port `/seasondq` as `/moderation season-disqualify`
Issue
-----
Closes #48
> #48: Port `/seasonDQ` as `/moderation season-disqualify`

- source/commands/moderation.js
Summary
-------
- Port `/penalty` as `/moderation xp-penalty`
Issue
-----
Closes #47
> #47: Port `/penalty` as `/moderation xp-penalty`

- source/commands/create-default.js
Summary
-------
- add `/create-default rank-roles`
- fix failure to create season with new company in /create-default
Issue
-----
Closes #63
> #63: Add `/create default-rank-roles`

- source/buttons/secondtoast.js
Summary
-------
- seconded toast includes toaster, but not seconder
- wasn't able to test solo
Issue
-----
Closes #69
> #69: seconded toast includes toaster, but not seconder

- source/embedHelpers.js
Summary
-------
- add BountyBot specific tips to pool
N/A, text changes
Issue
-----
Closes #72
> #72: add BountyBot specific tips

- package-lock.json
- package.json
Summary
-------
- update Discord.js to v14.13.0
Issue
-----
Closes #78
> #78: Update to Discord.js v14.13.0

- source/embedHelpers.js
Summary
-------
- add character overflow handling for scoreboards
Issue
-----
Closes #92
> #92: add character overflow handling for scoreboards

- source/commands/_commandDictionary.js
- source/commands/config-premium.js
- source/commands/config-server.js
- source/commands/tutorial.js
- source/constants.js
Summary
-------
- port `/config-premium`
Issue
-----
Closes #100
> #100: Port `/config-premium`

- source/commands/bounty.js
Summary
-------
- port `/list` as `/bounty list`
- considered listing all hunters with open bounties in the company (in a list in message content), but couldn't figure out the db query off-hand
Issue
-----
Closes #101
> #101: Port `/list`

- source/bot.js
- source/buttons/secondtoast.js
- source/commands/bounty.js
- source/commands/evergreen.js
- source/commands/moderation.js
- source/commands/toast.js
- source/models/companies/Company.js
- source/models/seasons/Season.js
Summary
-------
- add event handler for `GuildDelete`
Issue
-----
Closes #34
> #34: add event handler for `GuildDelete`

- source/commands/moderation.js
- source/embedHelpers.js
- source/models/users/Hunter.js
Summary
-------
- Port `/moderation user-report`
Issue
-----
Closes #112
> #112: Port `/moderation user-report`

- source/commands/premium.js
- source/commands/rank.js
Summary
-------
- update text for /premium
- fix /rank not being premium
Issue
-----
Closes #40
> #40: Update text for /premium

- source/bot.js
- source/classes/InteractionWrapper.js
- source/commands/_command_blueprint.js
- source/commands/about.js
- source/commands/bounty.js
- source/commands/commands.js
- source/commands/config-premium.js
- source/commands/config-server.js
- source/commands/create-default.js
- source/commands/data-policy.js
- source/commands/event.js
- source/commands/evergreen.js
- source/commands/feedback.js
- source/commands/moderation.js
- source/commands/premium.js
- source/commands/raffle.js
- source/commands/rank.js
- source/commands/reset.js
- source/commands/scoreboard.js
- source/commands/season-end.js
- source/commands/server-bonuses.js
- source/commands/stats.js
- source/commands/toast.js
- source/commands/tutorial.js
- source/commands/version.js
Summary
-------
- allow bot participants while not in prod mode
- report error and skip patch notes post if falsy `annoucnementsChannelId`
Issue
-----
Closes #123
> #123: Allow bot participants while not in prod mode

- README.md
- source/commands/about.js
- source/commands/tutorial.js
- source/constants.js
Summary
-------
- create constant for BountyBot invite URL and update to include include ManageServer (for access to AutoMod)
Issue
-----
Closes #129
> #129: Update join links to include ManageServer permission (for AutoMod)

- package-lock.json
- package.json
Summary
-------
- update discord.js to v14.14.0
Issue
-----
Closes #135
> #135: Update discord.js to v14.14.0

- source/buttons/secondtoast.js
- source/commands/bounty.js
- source/commands/evergreen.js
- source/commands/toast.js
Summary
-------
- double line break between categories
- bullet points
Issue
-----
Closes #131
> #131: improve formatting on rewards messages

- source/buttons/secondtoast.js
Summary
-------
- always filter seconder out of second toast
Issue
-----
Closes #132
> #132: always filter seconder out of second toast

- source/buttons/secondtoast.js
- source/selects/bountypost.js
Summary
-------
- update scoreboard after bounty post and toast seconding
Issue
-----
Closes #133
> #133: update scoreboard after bounty post and second toast

- ChangeLog.md
- source/buttons/secondtoast.js
- source/commands/bounty.js
- source/commands/evergreen.js
- source/commands/moderation.js
- source/commands/toast.js
Summary
-------
- add `/moderation bountybot-ban`
Issue
-----
Closes #124
> #124: add `/moderation bountybot-ban`

- ChangeLog.md
- source/commands/bounty/complete.js
- source/commands/bounty/edit.js
- source/commands/bounty/post.js
- source/commands/bounty/showcase.js
- source/commands/bounty/swap.js
- source/commands/bounty/takedown.js
- source/commands/evergreen/complete.js
- source/commands/evergreen/edit.js
- source/commands/evergreen/post.js
- source/commands/evergreen/showcase.js
- source/commands/evergreen/swap.js
- source/commands/evergreen/takedown.js
- source/commands/festival/close.js
- source/commands/festival/start.js
- source/commands/reset/serversettings.js
- source/models/bounties/Bounty.js
- source/models/companies/Company.js
- source/models/users/Hunter.js
- source/scripts/migrations/v2.5.0/migration.js
- source/util/embedUtil.js
Summary
-------
- make descriptions on bounties optional
- rename eventMultiplier to festivalMultiplier
Issue
-----
Closes #177 & Closes #147
> #177 & #147: database model updates

- source/models/bounties/Completion.js
- source/scripts/migrations/v2.6.0/migration2.js
Summary
-------
- Change type of Completion.bountyId to UUID
Issue
-----
Closes #189
> #189: Change Completion.bountyId to UUID

- package-lock.json
- package.json
Summary
-------
- update to discord.js v14.15.2
Issue
-----
Closes #209
> #209: Update to Discord.js v14.15.2

- package-lock.json
- package.json
Summary
-------
- update to Discord.js v14.15.3
Issue
-----
Closes #216
> #216: update to Discord.js v14.15.3

- ChangeLog.md
- source/commands/config-premium.js
- source/commands/reset/serversettings.js
- source/commands/toast.js
- source/models/bounties/Bounty.js
- source/models/companies/Company.js
- source/scripts/migrations/v2.7.0/migration.js
- source/util/embedUtil.js
Summary
-------
- customizable thumbnail images per company
Issue
-----
Closes #213
> #213: customizable thumbnail images per company

- ChangeLog.md
- source/items/_itemDictionary.js
- source/items/bounty-thumbnail.js
- source/models/bounties/Bounty.js
- source/scripts/migrations/v2.8.0/migration.js
- source/util/itemUtil.js
Summary
-------
- add Bounty Thumbnail item
Issue
-----
Closes #242
> #242: add Bounty Thumbnail item

- package-lock.json
- package.json
Summary
-------
- Update to discord.js v14.16.1
Issue
-----
Closes #245
> #245: Update to discord.js v14.16.1

- ChangeLog.md
- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/commands/bounty/edit.js
- source/commands/bounty/post.js
- source/commands/create-default/bountyboardforum.js
- source/commands/evergreen/complete.js
- source/commands/evergreen/edit.js
- source/commands/season-end.js
- source/commands/stats.js
- source/commands/toast.js
- source/items/xp-boost-epic.js
- source/items/xp-boost-legendary.js
- source/items/xp-boost.js
- source/models/seasons/Participation.js
- source/models/users/Hunter.js
- source/scripts/migrations/v2.8.0/migration3.js
Summary
-------
- Season End Shoutout: Most Posted Bounties
- fixed bounty posters receiving all item drops
- replaced local increment then save with Model.increment method
- fixed hunter query in /create-default bounty-board-forum
- fixed stat not incrementing for toastsSeconded
Issue
-----
Closes #237
> #237: Season End Shoutout: Most Posted Bounties

- source/commands/about.js
Summary
-------
- remove dead link to SillySalamndr twitter in /about
Issue
-----
Closes #243
> #243: remove dead link to SillySalamndr twitter in /about

- ChangeLog.md
- source/commands/season-end.js
- source/commands/toast.js
- source/models/seasons/Participation.js
- source/scripts/migrations/v2.8.0/migration4.js
Summary
-------
- Season End Shoutout: Most Toasts Raised
Issue
-----
Closes #236
> #236: Season End Shoutout: Most Toasts Raised

- package-lock.json
- package.json
Summary
-------
- update discord.js to v14.16.3
Issue
-----
Closes #253
> #253: update discord.js to v14.16.3

- source/logic/toasts.js
Summary
-------
- improve crit toast formula documentation
Issue
-----
Closes #263
> #263: improve crit toast formula documentation

- source/commands/about.js
- source/commands/premium.js
- source/commands/tutorial.js
- source/util/embedUtil.js
Summary
-------
- add last updated timestamp to /about, /premium, and /version
Issue
-----
Closes #262
> #262: add last updated timestamp to /about, /premium, and /version

- source/buttons/bbaddcompleters.js
- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/commands/bounty/post.js
- source/items/goal-initializer.js
- source/items/progress-in-a-can.js
- source/logic/bounties.js
- source/logic/goals.js
- source/logic/toasts.js
Summary
-------
- add embed as Goal Completion notification
- bounty board add completer button no longer returns a private confirmation in addition to its public confirmation
- Goal Initializer response text is now a Server Announcement
- Goal Initializer response text no longer references a deleted message
Issue
-----
Closes #278
> #278: improve Goal Completion notification

- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/logic/goals.js
- source/logic/toasts.js
- source/models/bounties/Bounty.js
- source/scripts/migrations/v2.9.0/migration2.js
Summary
-------
- show server goal progress bars on toast and bounty embeds
- move bounty poster to author field of embed
- fix crash in add completers button on bounty board
Issue
-----
Closes #286
> #286: show server goal progress bars on toast and bounty embeds

- source/buttons/bbaddcompleters.js
- source/buttons/bbcomplete.js
- source/buttons/bbremovecompleters.js
- source/buttons/bbshowcase.js
- source/buttons/bbtakedown.js
- source/commands/bounty/edit.js
- source/commands/bounty/post.js
- source/commands/bounty/showcase.js
- source/commands/bounty/takedown.js
- source/commands/evergreen/edit.js
- source/commands/evergreen/showcase.js
- source/commands/evergreen/takedown.js
- source/commands/item.js
- source/commands/moderation/takedown.js
- source/commands/raffle/byrank.js
- source/items/bonus-bounty-showcase.js
- source/items/bounty-thumbnail.js
Summary
-------
- applied awaitMessageComponent pattern to interaction collectors for the following benefits
- ability to acknowledge all interactions without risk of race condition (implemented in places that didn't significantly increase scope)
- improved typing of response values
- automatic expiry of ephemeral messages with message components
- the following flows work on critical path:
Issue
-----
Closes #304
> #304: apply awaitMessageComponent pattern to applicable interaction collectors

- package-lock.json
- package.json
Summary
-------
- update Discord.js to v14.18.0
Issue
-----
Closes #315
> #315: update Discord.js to v14.18.0

- source/buttons/bbaddcompleters.js
- source/buttons/bbcomplete.js
- source/buttons/bbremovecompleters.js
- source/buttons/bbshowcase.js
- source/buttons/secondtoast.js
- source/commands/bounty/addcompleters.js
- source/commands/bounty/complete.js
- source/commands/bounty/edit.js
- source/commands/bounty/list.js
- source/commands/bounty/post.js
- source/commands/create-default/bountyboardforum.js
- source/commands/evergreen/complete.js
- source/commands/evergreen/edit.js
- source/commands/evergreen/post.js
- source/commands/evergreen/showcase.js
- source/commands/evergreen/swap.js
- source/commands/evergreen/takedown.js
- source/context_menus/Give_Bounty_Credit.js
- source/items/progress-in-a-can.js
- source/logic/bounties.js
- source/logic/goals.js
- source/logic/index.js
- source/logic/toasts.js
- source/models/bounties/Bounty.js
- source/util/bountyUtil.js
- source/util/embedUtil.js
Summary
-------
- replace uses of `Bounty.asEmbed()` with `Bounty.embed()`
- fix type annotation on `updateBoardPosting` functions' parameters
- added dev mode skip to bounty board showcase button
- fix race condition between interaction acknowledgement and ephemeral message clean up in Bounty Board Add Completers
- fix evergreen completions clobbering old records of completions on `xpAwarded`
- fix bounty completions sending "+0 GP" reward messages
- evergreen bounty embeds now create a completers field for completions
- fixed an `undefined` in `/evergreen swap` response message
- evergreen bounties now contribute GP (for each completer)
- fix server goal progress bars sometimes finding the wrong goal
- creates consolidated function for finding current goal GP
- removes `database` …
> #298: replace uses of `Bounty.asEmbed()` with `Bounty.embed()`

- migrations/20250217170845-renameToRequiredGP.js
- source/items/goal-initializer.js
- source/logic/goals.js
- source/models/companies/Goal.js
Summary
-------
- rename column Goal.requiredContributions to Goal.requiredGP
Issue
-----
Closes #313
> #313: rename column Goal.requiredContributions to Goal.requiredGP

- source/buttons/secondtoast.js
- source/models/toasts/Seconding.js
Summary
-------
- update seconding reward string compilation
- changed reward section header style to heading2
Issue
-----
Closes #320
> #320: update seconding reward string compilation

- migrations/20250217170845-renameToRequiredGP.js
- source/buttons/bbcomplete.js
- source/commands/bounty/complete.js
- source/commands/bounty/edit.js
- source/commands/bounty/takedown.js
- source/commands/evergreen/complete.js
- source/commands/evergreen/edit.js
- source/commands/evergreen/showcase.js
- source/commands/evergreen/takedown.js
- source/commands/moderation/takedown.js
- source/items/goal-initializer.js
- source/logic/bounties.js
- source/logic/goals.js
- source/models/bounties/Bounty.js
- source/models/companies/Goal.js
Summary
-------
- consolidate bounty reward string compilation
- changed reward section heading style to heading2
- fix flows that relied on removed association `Bounty.Company`
- reapplied clobbered changes (removal of `Bounty.asEmbed()` and removal of `database` from `completeBounty()`)
- annotated parameter typing on `Bounty.calculateCompleterReward` and `Bounty.calculatePosterReward`
Issue
-----
Closes #319
> #319: consolidate bounty reward string compilation

- source/commands/_subcommand_blueprint.js
- source/commands/inventory.js
- source/logic/index.js
- source/logic/items.js
Summary
-------
- add `logicLyaer.items.getInventory()`
- fix typing in subcommand blueprint
> add `logicLayer.items.getInventory()`

- source/bot.js
- source/commands/reset/allhunterstats.js
- source/logic/hunters.js
Summary
-------
- create endpoint `deleteCompanyHunters()`
> create endpoint `deleteCompanyHunters()`

- source/bot.js
- source/logic/companies.js
Summary
-------
- create `deleteCompany` endpoint
- update convention in company interface: `guildId` -> `companyId`
> create `deleteCompany` endpoint

- source/commands/season-end.js
- source/logic/hunters.js
- source/util/scoreUtil.js
Summary
-------
- create endpoint `findCompanyHunters()`
> create endpoint `findCompanyHunters()`

- source/commands/item.js
- source/logic/items.js
Summary
-------
- create endpoint `findUserItemEntry()`
> create endpoint `findUserItemEntry()`

- source/bot.js
- source/logic/seasons.js
Summary
-------
- create endpoint `deleteCompanyParticipations()`
> create endpoint `deleteCompanyParticipations()`

- source/bot.js
- source/logic/bounties.js
Summary
-------
- add endpoint `deleteCompanyBounties()`
> add endpoint `deleteCompanyBounties()`

- source/commands/season-end.js
- source/logic/hunters.js
Summary
-------
- create endpoint `resetCompanyRanks()`
> create endpoint `resetCompanyRanks()`

- source/commands/reset/serversettings.js
- source/logic/companies.js
Summary
-------
- add endpoint `resetCompanySettings()`
> add endpoint `resetCompanySettings()`

- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/commands/evergreen/complete.js
- source/commands/toast.js
- source/context_menus/BountyBot_Stats.js
- source/context_menus/Raise_a_Toast.js
- source/items/progress-in-a-can.js
- source/logic/bounties.js
- source/logic/goals.js
- source/logic/seasons.js
- source/logic/toasts.js
- source/util/scoreUtil.js
Summary
-------
- remove direct logic layer imports from logic layer
- remove direct logic layer import from scoreUtil
- create endpoint `incrementSeasonStat()`
- fix undefined variable in BountyBot_Stats
Issue
-----
Closes #337
> #337: remove remaining direct imports from logic layer

- source/commands/reset/allhunterstats.js
- source/logic/seasons.js
Summary
-------
- add endpoint `deleteSeasonParticipations()`
> add endpoint `deleteSeasonParticipations()`

- source/commands/reset/allhunterstats.js
Summary
-------
- use findCompanyByPK endpoint in `/reset all-hunter-stats`
> use findCompanyByPK endpoint in `/reset all-hunter-stats`

- source/commands/moderation/gppenalty.js
- source/logic/goals.js
Summary
-------
- add endpoint `createGoalContribution()`
> add endpoint `createGoalContribution()`

- source/buttons/secondtoast.js
- source/logic/toasts.js
Summary
-------
- create endpoint `findToastByPK()`
> create endpoint `findToastByPK()`

- source/commands/moderation/gppenalty.js
- source/items/goal-initializer.js
- source/items/progress-in-a-can.js
- source/logic/goals.js
Summary
-------
- add endpoint `findCurrentServerGoal()`
> add endpoint `findCurrentServerGoal()`

- source/buttons/secondtoast.js
- source/logic/toasts.js
Summary
-------
- create endpoint `createSeconding()`
> create endpoint `createSeconding()`

- source/models/bounties/Bounty.js
- source/models/bounties/Completion.js
- source/models/companies/Company.js
- source/models/companies/Contribution.js
- source/models/companies/Goal.js
- source/models/companies/Rank.js
- source/models/seasons/Participation.js
- source/models/seasons/Season.js
- source/models/toasts/Recipient.js
- source/models/toasts/Seconding.js
- source/models/toasts/Toast.js
- source/models/users/Hunter.js
- source/models/users/Item.js
- source/models/users/User.js
Summary
-------
- add missing type import
- change Bounty.embed to async function
- reduce boilerplate in initModel
> model improvements

- source/buttons/secondtoast.js
- source/logic/toasts.js
Summary
-------
- create endpoint `findStaleToasteeIds()`
> create endpoint `findStaleToasteeIds()`

- source/buttons/bbtakedown.js
- source/commands/moderation/takedown.js
- source/logic/bounties.js
Summary
-------
- no dependence on the Bounty.Company association, removed fetches attempting to get them
Issue
-----
Closes #341
> #341: remove vestigial Bounty.Company associations

- source/buttons/bbcomplete.js
- source/buttons/bbremovecompleters.js
- source/buttons/bbshowcase.js
- source/buttons/bbtakedown.js
- source/commands/bounty/edit.js
- source/commands/bounty/takedown.js
- source/commands/evergreen/showcase.js
- source/items/bounty-thumbnail.js
- source/util/bountyUtil.js
Summary
-------
- implement endpoint `findBounty()` throughout codebase
> implement endpoint `findBounty()` throughout codebase

- source/commands/bounty/removecompleters.js
- source/commands/bounty/swap.js
- source/items/bounty-thumbnail.js
- source/models/bounties/Bounty.js
- source/util/bountyUtil.js
Summary
-------
- remove `database` from `Bounty.updatePosting()` parameters
> remove `database` from `Bounty.updatePosting()` parameters

- source/buttons/bbremovecompleters.js
- source/commands/bounty/removecompleters.js
- source/logic/bounties.js
Summary
-------
- add endpoint `deleteSelectedBountyCompletions()`
> add endpoint `deleteSelectedBountyCompletions()`

- source/bot.js
- source/logic/bounties.js
Summary
-------
- create endpoint `deleteCompanyCompletions()`
> create endpoint `deleteCompanyCompletions()`

- source/buttons/bbtakedown.js
- source/commands/bounty/takedown.js
- source/commands/evergreen/takedown.js
- source/commands/moderation/takedown.js
- source/logic/bounties.js
Summary
-------
- create endpoint `deleteBountyCompletions()`
> create endpoint `deleteBountyCompletions()`

- source/commands/evergreen/complete.js
- source/logic/bounties.js
Summary
-------
- create endpoint `bulkCreateCompletions()`
> create endpoint `bulkCreateCompletions()`

- source/commands/bounty/swap.js
- source/logic/bounties.js
Summary
-------
- create endpoint `bulkFindOpenBounties()`
> create endpoint `bulkFindOpenBounties()`

- source/commands/create-default/bountyboardforum.js
- source/logic/bounties.js
Summary
-------
- create endpoint `findCompanyBountiesByCreationDate()`
> create endpoint `findCompanyBountiesByCreationDate()`

- source/commands/moderation/userreport.js
- source/logic/bounties.js
Summary
-------
- create endpoint `findHuntersLastFiveBounties()`
> create endpoint `findHuntersLastFiveBounties()`

- source/commands/moderation/userreport.js
- source/logic/seasons.js
Summary
-------
- create endpoint `getDQCount()`
> create endpoint `getDQCount()`

- source/items/goal-initializer.js
- source/logic/goals.js
Summary
-------
- create endpoint `createGoal()`
> create endpoint `createGoal()`

- source/commands/bounty/post.js
- source/commands/evergreen/post.js
- source/logic/bounties.js
Summary
-------
- create endpoint `createBounty()`
> create endpoint `createBounty()`

- source/commands/moderation/seasondisqualify.js
- source/logic/seasons.js
Summary
-------
- create endpoint `disqualifyHunter()`
> create endpoint `disqualifyHunter()`

- source/commands/raffle/bylevel.js
- source/logic/hunters.js
Summary
-------
- create endpoint `findHuntersAtOrAboveLevel()`
> create endpoint `findHuntersAtOrAboveLevel()`

- source/buttons/bbcomplete.js
- source/buttons/bbremovecompleters.js
- source/buttons/bbshowcase.js
- source/commands/bounty/complete.js
- source/commands/bounty/edit.js
- source/commands/bounty/list.js
- source/commands/bounty/removecompleters.js
- source/commands/bounty/showcase.js
- source/commands/bounty/swap.js
- source/commands/create-default/bountyboardforum.js
- source/commands/evergreen/post.js
- source/items/bonus-bounty-showcase.js
- source/logic/bounties.js
- source/util/bountyUtil.js
Summary
-------
- add endpoint `findBountyCompletions`
- remove `database` from `showcaseBounty()`
> add endpoint `findBountyCompletions`

- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/commands/bounty/post.js
- source/commands/evergreen/complete.js
- source/commands/reset/allhunterstats.js
- source/commands/season-end.js
- source/commands/toast.js
- source/context_menus/Raise_a_Toast.js
- source/logic/bounties.js
Summary
-------
- create endpoint `findOneEvergreenBounty()`
- remove unused imports for `updateScoreboard()`
> create endpoint `findOneEvergreenBounty()`

- source/bot.js
- source/logic/toasts.js
Summary
-------
- create endpoint `deleteCompanyToastRecords()`
> create endpoint `deleteCompanyToastRecords()`

- source/logic/toasts.js
- source/util/textUtil.js
Summary
-------
- use `dateInPast()`
> use `dateInPast()`

- source/bot.js
- source/buttons/secondtoast.js
- source/commands/about.js
- source/commands/moderation/bountybotban.js
- source/commands/stats.js
- source/logic/goals.js
Summary
-------
- fixes found during regression test #416
> Test fixes v2.9.0

- source/commands/season-end.js
Summary
-------
- fix syntax error in guild reference in /season-end
> fix syntax error in guild reference in /season-end

- source/commands/bounty/swap.js
Summary
-------
- fix use before declaration in /bounty swap
> fix use before declaration in /bounty swap

- source/bot.js
- source/logic/bounties.js
- source/logic/goals.js
- source/logic/ranks.js
- source/logic/seasons.js
- source/logic/toasts.js
Summary
-------
- delete Goals and Contributions
- combine `deleteCompanyBounties` and `deleteCopanyCompletions`
- combine `deleteCompanySeasons` and `deleteCompanyParticiaptions`
- rename `deleteRanks` to `deleteCompanyRanks` and `deleteCompanyToastRecords` to `deleteCompanyToasts`
Issue
-----
Closes #430
> #430: On `GuildDelete` improvements

- source/logic/bounties.js
Summary
-------
- fix premium check for item drop limit
Issue
-----
Closes #431
> #431: fix premium check for item drop limit

- migrations/20250329232228-removeParanoid.js
- source/logic/companies.js
- source/models/bounties/Bounty.js
- source/models/companies/Company.js
- source/models/seasons/Season.js
Summary
-------
- remove paranoid Company, Season, and Bounty tables
Issue
-----
Closes #440
> #440: remove paranoid Company, Season, and Bounty tables

- source/frontend/commands/inventory.js
- source/frontend/commands/seasonal-ranks.js
- source/frontend/shared/dAPIRequests.js
Summary
-------
- consolidate "variable length message overflow handling"
Issue
-----
Closes #456
> #456: create validation function `contentOrFileMessagePayload()`

- source/frontend/commands/toast.js
- source/frontend/context_menus/Raise_a_Toast.js
- source/logic/toasts.js
Summary
-------
- move reward text generation and reloads from raiseToast to frontend
- fixed foreign key crash when including a not-yet-registered hunter in a `/toast`
> move reward text generation and reloads from `raiseToast()` to frontend

- migrations/20250521222620-renameVarianceThreshold.js
- source/database/models/companies/Rank.js
- source/frontend/commands/create-default/rankroles.js
- source/frontend/commands/raffle/byrank.js
- source/frontend/commands/rank/add.js
- source/frontend/commands/rank/edit.js
- source/frontend/commands/rank/remove.js
- source/frontend/commands/seasonal-ranks.js
- source/frontend/shared/dAPIRequests.js
- source/frontend/shared/toBeMoved.js
- source/logic/ranks.js
Summary
-------
- rename `Rank.varianceThreshold` to `threshold`
Issue
-----
Closes #507
> #507: rename `Rank.varianceThreshold` to `threshold`
