- source/commands/_commandDictionary.js
- source/commands/feedback.js
- source/commands/scoreboard.js
- source/commands/stats.js
- source/constants.js
- source/embedHelpers.js
- source/helpers.js
- source/models/guilds/Guild.js
- source/models/users/Hunter.js
Summary
-------
- ported /stats with following changes
- added level property to Guild instead of reimplementing BotHunter
- /stats shows the self-embed when a user specifies themself as an argument
- guildstats embed is now blurple instead of user's color
- implemented generateTextBar instead of buildXPBar (more general)
- added 404 early outs, allowing lazier hunter generation
Issue
-----
Closes #15
> #15: port /stats

- database.js
- source/classes/InteractionWrapper.js
- source/commands/_commandDictionary.js
- source/commands/about.js
- source/commands/bounty.js
- source/commands/commands.js
- source/commands/create-bounty-board.js
- source/commands/scoreboard.js
- source/commands/stats.js
- source/commands/version.js
- source/constants.js
- source/embedHelpers.js
- source/helpers.js
- source/modals/_modalDictionary.js
- source/modals/bountypostmodal.js
- source/models/bounties/Bounty.js
- source/models/bounties/Completion.js
- source/models/guilds/Guild.js
- source/models/guilds/GuildRank.js
- source/models/users/Hunter.js
- source/models/users/User.js
- source/scripts/updateWiki.js
- source/selects/_selectDictionary.js
- source/selects/bountypostselect.js
- wiki/Commands.md
Summary
-------
- ported `/bounty post`
- includes slash command, bounty slot select, and input modal
- added models for Bounty, GuildRank, and Completion
- GuildRank now uses a composite primary key of guildId + varianceThreshold
- Completion is the combination of PendingCompleter and BountyCompletion
- `/create-bounty-board` now populates with posts for existing bounties
- `/create-bounty-board` now creates a forum in ListView as default (shows bounty posts better than GalleryView)
- split `hunter.isRankEligible` from `hunter.rank` (now `INTEGER | NULL` from `STRING | NULL`)
Issue
-----
Closes #2
> #2: port `/bounty post`

- database.js
- source/buttons/_buttonDictionary.js
- source/buttons/secondtoast.js
- source/commands/_commandDictionary.js
- source/commands/bounty.js
- source/commands/stats.js
- source/commands/toast.js
- source/constants.js
- source/embedHelpers.js
- source/helpers.js
- source/models/bounties/Bounty.js
- source/models/bounties/Completion.js
- source/models/guilds/Guild.js
- source/models/guilds/GuildRank.js
- source/models/toasts/Toast.js
- source/models/toasts/ToastRecipient.js
- source/models/toasts/ToastSeconding.js
- source/models/users/Hunter.js
- source/models/users/User.js
Summary
-------
- added /toast
- added seconding toasts
- implemented `findOrCreate`
- improved foreignKey configuration of database models
- added rankmoji to scoreboard
- /toast from empty database
- second toast
Issue
-----
Closes #25
> #25: `/toast` and seconding toasts

- source/commands/_commandDictionary.js
- source/commands/premium.js
Summary
-------
- port /premium command (text to be updated after perk list and sponsorship system finalized)
Issue
-----
Closes #29
> #29: Port `/premium`

- source/buttons/secondtoast.js
- source/classes/InteractionWrapper.js
- source/commands/bounty.js
- source/commands/toast.js
- source/helpers.js
- source/modals/_modalDictionary.js
- source/modals/bountyeditmodal.js
- source/modals/bountypostmodal.js
- source/models/bounties/Bounty.js
- source/models/guilds/Guild.js
- source/selects/_selectDictionary.js
- source/selects/bountyeditselect.js
Summary
-------
- added `/bounty edit` flow
- made CommandWrapper's subcommands.optionsInput optional
- removed `isRankEligible` from query in `findOrCreate` for hunters
- fixed bountypostmodal not reporting non-integer error for only one timestamp
- fixed mangling of event ids due to storing them as numbers
- added support for `@silent` announcements
Issue
-----
Closes #4
> #4: Port `/edit` as `/bounty edit` flow

- source/commands/bounty.js
- source/models/bounties/Bounty.js
- source/selects/_selectDictionary.js
- source/selects/bountytakedown.js
Summary
-------
- added `/remove` as `/bounty take-down`
Issue
-----
Closes #8
> #8: Port `/remove` as `/bounty take-down`

- database.js
- source/commands/_commandDictionary.js
- source/commands/bounty.js
- source/commands/create-bounty-board.js
- source/commands/evergreen.js
- source/commands/stats.js
- source/helpers.js
- source/modals/_modalDictionary.js
- source/modals/bountyeditmodal.js
- source/modals/bountypostmodal.js
- source/modals/evergreeneditmodal.js
- source/modals/evergreenpost.js
- source/models/bounties/Bounty.js
- source/models/bounties/Completion.js
- source/models/guilds/Guild.js
- source/models/users/Hunter.js
- source/selects/_selectDictionary.js
- source/selects/bountypostselect.js
- source/selects/evergreeneditselect.js
- source/selects/evergreentakedown.js
Summary
-------
- added /evergreen supercommand (included `post`, `edit`, `complete`, and `take-down`)
- the bounty board now pins the evergreen bounties instead of the scoreboard
- added length validations to bounty title
Issue
-----
Closes #26
> #26: Added `/evergreen`

- source/commands/rank.js
Summary
-------
- adds `/rank info` and `/rank edit`
- had to pivot away from "show all ranks in UI before edit" because edit had to use slash command options because modals don't have role auto-complete
Issue
-----
Closes #20 & #21
> #20 & #21: adds `/rank info` and `/rank edit`

- source/models/bounties/Bounty.js
- source/models/bounties/Completion.js
- source/models/toasts/Toast.js
Summary
-------
- switch auto-incrementing id column types to UUID
Issue
-----
Closes #38
> #38: Use UUID datatype for model ids

- source/commands/_commandDictionary.js
- source/commands/data-policy.js
- wiki/Data-Policy.md
Summary
-------
- Ported `/data-policy` command
Issue
-----
Closes #12
> #12: Port `/data-policy`

- source/commands/_commandDictionary.js
- source/commands/raffle.js
- source/models/guilds/Guild.js
- source/selects/_selectDictionary.js
- source/selects/rafflerank.js
Summary
-------
- add `/raffle by-level`
- add `/raffle by-rank`
- add `/raffle announce-upcoming`
Issue
-----
Closes #30
> #30: Port `/raffle`

- source/commands/_commandDictionary.js
- source/commands/server-bonuses.js
- source/embedHelpers.js
- source/models/guilds/Guild.js
Summary
-------
- add `/server-bonuses` (name change to disambiguate from Discord scheduled events)
Issue
-----
Closes #9
> #9: Port `/event-info` as `/server-bonuses`

- source/commands/toast.js
- source/helpers.js
- source/modals/bountyeditmodal.js
- source/modals/bountypostmodal.js
- source/modals/evergreeneditmodal.js
- source/modals/evergreenpost.js
Summary
-------
- Add AutoMod support for toasts, bounties, and evergreen bounties
Issue
-----
Closes #42
> #42: Add AutoMod support for toasts, bounties, and evergreen bounties

- source/buttons/secondtoast.js
- source/commands/bounty.js
- source/commands/evergreen.js
- source/commands/moderation.js
- source/commands/toast.js
- source/selects/bountytakedown.js
Summary
-------
- fix crash on bounty complete if no bounty board
- allow findOrCreate to create associated entities
Issue
-----
Closes #51
> #51: fix crash on bounty complete if no bounty board

- source/commands/_commandDictionary.js
- source/commands/season-end.js
Summary
-------
- ported `/next-season` as `/season-end`
- decided not to implement delay functionality in favor of scheduling functionality in the future (#87)
Issue
-----
Closes #82
> #82: Port `/next-season`

- source/commands/_commandDictionary.js
- source/commands/config-server.js
Summary
-------
- Port `/config-server`
Issue
-----
Closes #99
> #99: Port `/config-server`

- source/commands/_commandDictionary.js
- source/commands/reset.js
- source/models/companies/Company.js
Summary
-------
- port `/reset`
- decided `/reset all-bounties` was not part of MVP
- removed rewards code draft
Issue
-----
Closes #103
> #103: Port `/reset`

- database.js
- source/buttons/secondtoast.js
- source/commands/bounty.js
- source/commands/config-server.js
- source/commands/create-default.js
- source/commands/evergreen.js
- source/commands/moderation.js
- source/commands/reset.js
- source/commands/season-end.js
- source/commands/stats.js
- source/commands/toast.js
- source/constants.js
- source/embedHelpers.js
- source/helpers.js
- source/models/companies/Company.js
- source/models/seasons/Season.js
- source/models/seasons/SeasonParticipation.js
- source/models/toasts/Toast.js
- source/models/users/Hunter.js
- source/selects/bountypost.js
- source/selects/bountytakedown.js
- source/selects/modtakedown.js
Summary
-------
- resolve circular association between Company and Season (by removing `Company.seasonId` and `Company.lastSeasonId`)
- replace `Hunter.seasonParticipationId` with more detailed queries
- replace `Toast.recipeients` and `Toast.rewardedRecipient` virtuals with associations
- move `Hunter.seasonDQCount` to `SeasonParticipation.dqCount`
Issue
-----
Closes #91
> #91: improve model definitions

- source/buttons/secondtoast.js
- source/commands/bounty.js
- source/commands/evergreen.js
- source/commands/toast.js
Summary
-------
- fix crash if creating Hunter while associated User already exists
Issue
-----
Closes #110
> #110: fix crash if creating Hunter if associated User already exists

- ChangeLog.md
- source/commands/bounty.js
Summary
-------
- /bounty list defaults to own bounties
Issue
-----
Closes #127
> #127: /bounty list defaults to own bounties

- ChangeLog.md
- source/buttons/secondtoast.js
- source/commands/bounty.js
- source/commands/event.js
- source/commands/evergreen.js
- source/commands/toast.js
Summary
-------
- make rewards thread messages silent
Issue
-----
Closes #134
> #134: Make rewards thread messages silent

- ChangeLog.md
- source/selects/bountyedit.js
Summary
-------
- convert `/bounty edit` feedback to ephemeral
Issue
-----
Closes #153
> #153: Convert `/bounty edit` feedback to ephemeral

- package-lock.json
- package.json
- source/models/users/Hunter.js
Summary
-------
- update discord.js to v6.35.1
- split level-up reward texts onto new lines
Issue
-----
Closes #121
> #121: update discord.js to v6.35.1

- ChangeLog.md
- source/commands/bounty/complete.js
- source/commands/create-default/bountyboardforum.js
- source/models/companies/Company.js
- source/scripts/migrations/v2.1.0/migration.js
- source/selects/bountypost.js
- source/util/scoreUtil.js
Summary
-------
- use forum thread tags to allow searching for open bounties
Issue
-----
Closes #77
> #77: use forum thread tags to allow searching for open bounties

- ChangeLog.md
- source/models/bounties/Bounty.js
Summary
-------
- fix crash on edit bounty with archived thread
Notes
-------
Discord channel name edit rate limiting seems to cause thread name updates to be skipped if many edits are made quickly.
Issue
-----
Closes #163
> #163: fix crash on edit bounty with archived thread

- ChangeLog.md
- source/buttons/secondtoast.js
- source/commands/stats.js
- source/models/toasts/Toast.js
- source/scripts/migrations/v2.3.0/migration.js
Summary
-------
- added Most Seconded Toast to /stats (both self and others)
- reorganized stats embeds (both self and others) to be more readable
- fix crash on viewing own stats
Issue
-----
Closes #80
> #80: add "most seconded toast"

- source/commands/bounty/complete.js
Summary
-------
- use `.deferReply()` in `/bounty complete` to avoid unknown interaction error 
Issue
-----
Closes #172
> #172: defer reply on `/bounty complete` to avoid "Unknown interaction" error

- source/commands/create-default/bountyboardforum.js
Summary
-------
- add eyes emoji as default emoji in bounty board forum
- `/create-default bounty-board-forum` creates a forum with :eyes: as default emoji
Issue
-----
Closes #184
> #184: add eyes emoji as default emoji in bounty board forum

- ChangeLog.md
- source/bot.js
- source/buttons/secondtoast.js
- source/commands/about.js
- source/commands/bounty/addcompleters.js
- source/commands/bounty/complete.js
- source/commands/bounty/edit.js
- source/commands/bounty/post.js
- source/commands/bounty/takedown.js
- source/commands/evergreen/complete.js
- source/commands/evergreen/post.js
- source/commands/evergreen/takedown.js
- source/commands/rank/add.js
- source/commands/toast.js
- source/commands/tutorial.js
- source/constants.js
Summary
-------
- add links to commands in description and in feedback messages
Issue
-----
Closes #183
> #183: add links to commands in description and in feedback messages

- source/bot.js
- source/buttons/_buttonDictionary.js
- source/buttons/_button_blueprint.js
- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/classes/InteractionWrapper.js
- source/commands/bounty/complete.js
- source/commands/bounty/post.js
- source/models/bounties/Bounty.js
- source/selects/_select_blueprint.js
Summary
-------
- add "Complete" button to bounty board threads
- optimize `/bounty complete` to avoid fetching same hunters twice
Issue
-----
Closes #179
> #179: add "Complete" button to bounty board threads

- ChangeLog.md
- source/buttons/bbcomplete.js
- source/commands/bounty/complete.js
- source/commands/bounty/edit.js
- source/commands/bounty/post.js
- source/commands/bounty/swap.js
- source/commands/evergreen/complete.js
- source/commands/evergreen/swap.js
- source/models/bounties/Bounty.js
- source/util/embedUtil.js
Summary
-------
- on completion of a bounty, grant the poster 1 bonus XP for each of: description, image URL, and timestamp set that are filled
Issue
-----
Closes #178
> #178: on completion, bounties grant their poster bonus XP for filled optional fields

- source/buttons/_buttonDictionary.js
- source/buttons/bbtakedown.js
- source/commands/bounty/post.js
- source/models/bounties/Bounty.js
Summary
-------
- add "Take Down" button to bounty board threads
Issue
-----
Closes #181
> #181: add "Take Down" button to bounty board threads

- ChangeLog.md
- source/buttons/_buttonDictionary.js
- source/buttons/bbaddcompleters.js
- source/buttons/bbremovecompleters.js
- source/commands/bounty/post.js
- source/commands/create-default/bountyboardforum.js
- source/models/bounties/Bounty.js
Summary
-------
- Add "Credit Bounty Hunters" button
- Add "Uncredit bounty Hunters" button
Issue
-----
Closes #180
> #180: add "Credit Bounty Hunters" and "Uncredit Bounty Hunters" buttons to bounty board threads

- ChangeLog.md
- source/buttons/_buttonDictionary.js
- source/buttons/bbaddcompleters.js
- source/buttons/bbremovecompleters.js
- source/buttons/bbshowcase.js
- source/commands/bounty/post.js
- source/commands/create-default/bountyboardforum.js
- source/models/bounties/Bounty.js
Summary
-------
- add "showcase" button to bounty threads
Issue
-----
Closes #182
> #182: add "showcase" button to bounty threads

- source/commands/bounty/complete.js
- source/models/bounties/Bounty.js
Summary
-------
- fix attempts to modify archived threads in `/bounty complete` if thread is archived before completion
- created logic to avoid unnecessary unarchive requests
Issue
-----
Closes #196
> #196: fix `/bounty complete` attempts to modify an archived thread

- ChangeLog.md
- source/buttons/bbaddcompleters.js
- source/buttons/bbcomplete.js
- source/buttons/bbremovecompleters.js
- source/buttons/bbshowcase.js
Summary
-------
- fix crash when using bounty board buttons
Issue
-----
Closes #202
> #202: fix crash when using bounty board buttons

- ChangeLog.md
- source/buttons/bbcomplete.js
- source/commands/_commandDictionary.js
- source/commands/bounty/complete.js
- source/commands/item.js
- source/items/_itemDictionary.js
- source/items/xp-boost-epic.js
- source/items/xp-boost-legendary.js
- source/items/xp-boost.js
Summary
-------
- added XP Boost, Epic XP Boost, and Legendary XP Boost items; these add XP to the hunter in the used guild
- item drops now roll a pool (eg colorizers vs xp boosts) before rolling which item in the pool to award the user
Issue
-----
Closes #207
> #207: add XP Boost items

- ChangeLog.md
- source/buttons/bbcomplete.js
- source/buttons/bbshowcase.js
- source/commands/bounty/complete.js
Summary
-------
- if no bounty board, place rewards in thread
- if bounty board and completed by slash command, mention completion in non-ephemeral message
- change bounty board completion button to take channel as input in which to announce bounty completion
- fix several crashes associated with item drops
Issue
-----
Closes #205
> #205: redesign responses to bounty completion

- ChangeLog.md
- source/commands/item.js
Summary
-------
- preview profile colorizer colors in /item embed
Issue
-----
Closes #223
> #223: preview profile colorizer colors in /item embed

- ChangeLog.md
- source/commands/bounty/edit.js
Summary
-------
- `/bounty edit` leaves an audit message in bounty board thread
- fixed a crash on editing a bounty with empty string as description
Issue
-----
Closes #226
> #226: `/bounty edit` leaves an audit message in bounty board thread

- ChangeLog.md
- source/buttons/bbaddcompleters.js
- source/commands/bounty/addcompleters.js
- source/commands/create-default/bountyboardforum.js
- source/commands/toast.js
- source/util/textUtil.js
Summary
-------
- send a audit message in bounty board thread on add completers
- implement listifyEN
- fix crash in /create-default bounty-board-forum
Issue
-----
Closes #224, Closes #229
> #224 & #229: send a audit message in bounty board thread on add completers, implement listifyEN

- ChangeLog.md
- source/buttons/bbremovecompleters.js
- source/commands/bounty/removecompleters.js
Summary
-------
- removing completers leaves audit message in bounty board thread
Issue
-----
Closes #225
> #225: removing completers leaves audit message in bounty board thread

- source/buttons/bbcomplete.js
- source/commands/bounty/complete.js
- source/items/_itemDictionary.js
- source/items/loot-box.js
- source/items/unidentified-item.js
- source/util/itemUtil.js
Summary
-------
- add Unidentified Item and Loot Box items
- changed drop table to explicit whitelist to avoid circular dependency
- quick sanity checking implies drop table frequencies aren't inverted and all pools appear reachable
Issue
-----
Closes #232
> #232: add Unidentified Item and Loot Box

- ChangeLog.md
- source/scripts/migrations/v2.8.0/migration2.js
Summary
-------
- Migrate Light Green Profile Colorizers to Light Grey Profile Colorizers
Issue
-----
Closes #239
> #239: Migrate Light Green Profile Colorizers to Light Grey Profile Colorizers

- package-lock.json
- package.json
Summary
-------
- update to discord.js v14.16.2
Issue
-----
Closes #248
> #248: update to discord.js v14.16.2

- source/util/embedUtil.js
Summary
-------
- remove custom handling for "Known Issues" section of version notes
Issue
-----
Closes #275
> #275: remove custom handling for "Known Issues" section of version notes

- ChangeLog.md
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/logic/toasts.js
Summary
-------
- fix crashes when using /toast, /bounty complete, or seconding a toast in a thread
Issue
-----
Closes #293
> #293: fix crashes when using /toast, /bounty complete, or seconding a toast in a thread

- source/items/goal-initializer.js
- source/logic/goals.js
- source/models/companies/Contribution.js
- source/util/embedUtil.js
Summary
-------
- switch from goal progress only by correct type to Goal Points
Issue
-----
Closes #282
> #282: switch from goal progress only by correct type to Goal Points

- source/commands/item.js
Summary
-------
- prevent using items in a server joined less than a day ago
Issue
-----
Closes #277
> #277: prevent using items in a server joined less than a day ago

- ChangeLog.md
- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/commands/item.js
- source/commands/moderation/gppenalty.js
- source/commands/moderation/index.js
- source/commands/moderation/revokegoalbonus.js
- source/logic/toasts.js
- source/util/embedUtil.js
Summary
-------
- add `/moderation revoke-goal-bonus` and `/moderation gp-penalty`
- fix validation for recent join item disable
- fix no contributions on goal showing as null instead of 0
Issue
-----
Closes #285
> #285: add goal moderation commands

- migrations/20250217170845-renameToRequiredGP.js
- source/commands/toast.js
- source/context_menus/Raise_a_Toast.js
- source/items/goal-initializer.js
- source/logic/goals.js
- source/logic/toasts.js
- source/models/companies/Goal.js
- source/models/toasts/Toast.js
Summary
-------
- consolidate toast reward string compilation
- switch section heading styling from "bold + underline" to "heading2"
- fix crash in `raiseToast`
- based on `ntseng/issue313` to avoid conflict with database column rename
Issue
-----
Closes #318
> #318: consolidate toast reward string compilation

- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/commands/evergreen/complete.js
- source/commands/toast.js
- source/context_menus/Raise_a_Toast.js
- source/items/progress-in-a-can.js
- source/logic/toasts.js
- source/models/companies/Goal.js
- source/models/toasts/Toast.js
Summary
-------
- move embed building out of `raiseToast()`
- consolidated the generation of the following message payload components
- toast embed
- goal completion embed
- toast seconding action row
Issue
-----
Closes #321
> #321: move embed building out of `raiseToast()`

- ChangeLog.md
- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/commands/bounty/post.js
- source/commands/create-default/scoreboardreference.js
- source/commands/evergreen/complete.js
- source/commands/moderation/userreport.js
- source/commands/reset/allhunterstats.js
- source/commands/scoreboard.js
- source/commands/season-end.js
- source/commands/stats.js
- source/commands/toast.js
- source/context_menus/BountyBot_Stats.js
- source/context_menus/Raise_a_Toast.js
- source/models/companies/Company.js
- source/models/users/Hunter.js
- source/util/embedUtil.js
Summary
-------
- move `buildModStatsEmbed()` to `Hunter.modStatsEmbed()`
- move `buildCompanyStatsEmbed()` to `Company.statsEmbed()`
This is Ugly but is Scheduled to Be Refactored Later
------------
- `company` removed from `updateScoreboard()` parameters to avoid circular dependency with Company (which needs `ihpAuthorPayload` among others)
- added `logicLayer` as parameter for `buildSeasonalScoreboardEmbed()` and `buildOverallScoreboardEmbed()`
Issue
-----
Closes #310
> #310: move `buildModStatsEmbed()` to `Hunter.modStatsEmbed()`

- source/buttons/bbaddcompleters.js
- source/commands/bounty/addcompleters.js
- source/context_menus/Give_Bounty_Credit.js
Summary
-------
- fix crash on add completers button in archived thread
- add missing type annotation imports
> fix crash on add completers button in archived thread

- source/buttons/secondtoast.js
- source/logic/toasts.js
Summary
-------
- create endpoint `wasAlreadySeconded()`
> create endpoint `wasAlreadySeconded()`

- source/buttons/bbtakedown.js
- source/buttons/secondtoast.js
- source/commands/bounty/post.js
- source/commands/bounty/takedown.js
- source/commands/evergreen/complete.js
- source/commands/moderation/bountybotban.js
- source/commands/moderation/seasondisqualify.js
- source/commands/moderation/takedown.js
- source/commands/moderation/xppenalty.js
- source/items/xp-boost-epic.js
- source/items/xp-boost-legendary.js
- source/items/xp-boost.js
- source/logic/seasons.js
Summary
-------
- add endpoint `changeSeasonXP()`
- fix skip DMing bot check always returning true
> add endpoint `changeSeasonXP()`

- source/commands/season-end.js
- source/logic/seasons.js
Summary
-------
- create endpoint `findFirstPlaceParticipation()`
- move `changeSeasonXP()` from Read block to Update block of seasons interface
> create endpoint `findFirstPlaceParticipation()`

- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/commands/bounty/post.js
- source/commands/create-default/scoreboardreference.js
- source/commands/evergreen/complete.js
- source/commands/reset/allhunterstats.js
- source/commands/scoreboard.js
- source/commands/season-end.js
- source/commands/toast.js
- source/context_menus/Raise_a_Toast.js
- source/logic/hunters.js
- source/models/companies/Company.js
- source/util/embedUtil.js
Summary
-------
- create (temporary) `findCompanyHuntersByDescendingXP()` to remove `database` from `updateScoreboard()` and `buildOverallScoreboardEmbed()`
- made `updateScoreboard()`, `buildSeasonalScoreboardEmbed()` and `buildOverallScoreboardEmbed()` into `Company` methods
> remove `database` from `updateScoreboard()` and `buildOverallScoreboardEmbed()`

- source/commands/bounty/addcompleters.js
- source/commands/bounty/complete.js
- source/commands/bounty/post.js
- source/commands/bounty/removecompleters.js
- source/context_menus/Give_Bounty_Credit.js
- source/logic/bounties.js
Summary
-------
- implement `findBounty()` in more places
- rename properties in object bountyInfo to `userId` and `companyId` to match entity name
Future Work
--------
- Discovered `findBounty()` is being called for two different use-cases, which unnecessarily increases implementation complexity, wrote up #388 to record
> implement `findBounty()` in more places

- source/items/goal-initializer.js
Summary
-------
- implement `getParticipantCount()` in Goal Initializer
The existing code was originally incorrectly read, making it look like ties in placements would reduce the Participant count returned. In reality, ties are placed at the lowest placement they tie at (instead of "1, 2, 2", it would be "I, 3, 3"), which would give a correct count, but is still a more confusion way to achieve the count than the direct Participant count endpoint.
> implement `getParticipantCount()` in Goal Initializer

- source/commands/season-end.js
- source/logic/seasons.js
Summary
-------
- create endpoint `findParticipationWithTopParticipationStat()`
> create endpoint `findParticipationWithTopParticipationStat()`

- source/commands/create-default/rankroles.js
- source/commands/moderation/seasondisqualify.js
- source/commands/raffle/byrank.js
- source/commands/rank/add.js
- source/commands/rank/info.js
- source/commands/season-end.js
- source/commands/stats.js
- source/context_menus/BountyBot_Stats.js
- source/logic/hunters.js
- source/logic/ranks.js
- source/logic/seasons.js
- source/models/companies/Company.js
- source/util/scoreUtil.js
Summary
-------
- create endpoint `findHunterIdsAtOrAboveRank()`
- fix hunter rank disqualification validation (`isRankDisqualified` had been moved from `Hunter` to `Participation`)
- fixed query directionality of `findHunterIdsAtOrAboveRank()`
- `/raffle by-rank` was incorrectly using low rank indices as the easy to achieve ranks (contrary to convention in database)
- removed extra query case in `findAllRanks()` by reversing the order in which ranks are presented in `/raffle by-rank`
- ranks were originally presented in ascending difficulty to obtain to nudge bot managers to run more accessible raffles, but the maintainability streamlining is more valuable considering the low effect of the nudge due to bot managers being nudged to announce raffles ahead of time
-  fixed scoreboard …
> create endpoint `findHunterIdsAtOrAboveRank()`

- ChangeLog.md
- source/logic/bounties.js
- source/util/textUtil.js
Moved the roll code into a separate function to better manage item rolls in the logic layer, since this code (other than roll rate) should function the same regardless of the person being rolled for.
I've added some convenience functions for calculating dates which are not required to be done in this pull request, but were done here due to them being convenient.
Includes a fix for not pulling the `season` data.
Fixes #279
Summary
-------
(Include a summary of the work done or the reasoning for the pivot here)
Issue
-----
Closes #279
> #279 & #409: add time based item drop rate limiting

- source/models/bounties/Bounty.js
Summary
-------
-  avoid crash if Bounty's embed's Completers field overflows
Pivots
-------
Decided to pivot away from user validation: on bounty render is a fairly difficult place to predict for database updates to be happening and checking if a user is in a guild requires fetching the entire guild member (a dAPI "are these members in this guild?" endpoint would be ideal for that).
Also decided to do a full replacement of text to avoid the string modification problem that only really adds "completer order politics".
Issue
-----
Closes #332
> #332: avoid crash if Bounty's embed's Completers field overflows

- source/commands/bounty/post.js
- source/commands/evergreen/post.js
Summary
-------
- only nudge members who can manage the bot to create a bounty board
> only nudge members who can manage the bot to create a bounty board

- source/commands/bounty/list.js
Summary
-------
- fix incorrect function name in `/bounty list`
> fix incorrect function name in `/bounty list`

- source/buttons/bbcomplete.js
- source/buttons/secondtoast.js
- source/commands/bounty/complete.js
- source/commands/evergreen/complete.js
- source/commands/toast.js
- source/context_menus/Raise_a_Toast.js
- source/logic/goals.js
- source/models/companies/Company.js
Summary
-------
- fix false positive on existing Server Goal check in Goal Initializer
- fix completed goals being shown on scoreboards
- remove clamping to requiredGP on GP gain updates
- clamping was previously added because having the existing GP be above the required GP "looked buggy", but a realistic case where the GP could be above the threshold was found during testing: if type doubling or another feature increased the GP gain above the remaining quota. in this case, it recognizes hunter contributions better if it shows the over-contribution
Issue
-----
Closes #426
> #426: fix false positive on existing Server Goal check in Goal Initializer

- source/commands/bounty/edit.js
- source/commands/bounty/post.js
- source/commands/evergreen/edit.js
- source/commands/evergreen/post.js
- source/commands/feedback.js
- source/context_menus/Give_Bounty_Credit.js
- source/context_menus/Raise_a_Toast.js
- source/items/bounty-thumbnail.js
Summary
-------
- fix crashes on modal expiry in the following places:
- `/bounty edit`
- `/bounty post`
- `/evergreen edit`
- `/evergreen post`
- Give Bounty Credit context menu
- Raise a Toast context menu
- Bounty Thumbnail item (catch/finally blocks were on the wrong layer)
- ignore thrown `InteractionCollectorError`s in the following places:
- `/evergreen post`
- `/feedback` bug report
- `/feedback` feature request
- Give Bounty Credit context menu
- Raise a Toast context menu
We, unfortunately, don't have a way to close expired modals, so users who try to submit those afterward will see a "the application didn't respond" on the modal (but no error on our side).
Issue
-----
Closes #425
> #425: fix crash on uncaught modal expiry error

- source/commands/config-premium.js
Summary
-------
- disable embeded url previews in /config-premium's response message
Issue
-----
Closes #422
> #422: disable embeded url previews in /config-premium's response message

- source/commands/raffle/byrank.js
Summary
-------
- catch Sequelize error on non-existent rank reload during `/raffle by-rank`
- move "nonemoji rank emoji" error handling to a DM, as the ephemeral message that would have held the error message gets cleaned up
This is a blocker for #427, which will be working in the same lines of code.
Had to change from `rankIndex` as select value to `varianceThreshold` to be able to detect missing ranks. This is likely pointing at changing a column on Hunter (in v2.10.0), given how volatile `rankIndex` is.
~~I'll need help testing the racing on this one. Also, I looked, but couldn't find any documentation on what Sequelize does if we try to reload an instance who's been deleted.~~ Sequelize throws an error (unhelpfully only containing the vague …
> #429: add early out if rank goes missing during `/raffle by-rank`

- source/commands/config-premium.js
- source/models/companies/Company.js
- source/models/users/Hunter.js
Summary
-------
- recalculate hunter levels after setting level threshold multiplier
- add validation to reject 0 and negative numbers in level threshold multiplier
- allow rest of command to resolve if given invalid bounty slots input
Issue
-----
Closes #424
> #424: `/config premium` improvements

- source/commands/festival/close.js
- source/commands/festival/start.js
Summary
-------
- `/festival close` and `/festival open` now update the scoreboard appropriately
Issue
-----
Closes #423
> #423: `/festival close` and `/festival open` now update the scoreboard appropriately

- migrations/20250402165105-addTimestampsToGoals.js
- source/bot.js
- wiki/Developers.md
Summary
-------
- add migration for adding `createdAt` and `updatedAt` columns to `Goal` and `Contribution`
- ~~create new tables by synching database models on startup~~
- ~~this solution is considered non-ideal because it opens the problem of "bot shards racing to update the tables"~~
Later research discovered the following (thanks @doubledh!):
- SQL logging can be turned on for migrations by adding `logging: true` to the env the migration is being run in (in `config/config.json`). The default for this was left off because it throws a deprecation error into the console on normal startup.
- The `SQLITE_ERROR: incomplete input` was coming from the `bulkUpdate` in the `addTimestampsToGoals` migration being run with an empty `values` parameter. That migration was being run before …
> Workaround create table failure

- source/buttons/bbcomplete.js
Summary
-------
This was found while investigating the April 2nd Unknown Interaction, but I don't think it's the same one. This one happens because `interaction` is acknowledged twice (once if the bounty isn't found, again on clean up), but the one being looked for is on `collectedInteraction` (the payload being sent is the rewards message).
I also wasn't able find the original Unknown Interaction.
> fix unknown interaction in bounty board complete

- package-lock.json
- package.json
Summary
-------
- update sequelize to v6.37.7
> update sequelize to v6.37.7

- ChangeLog.md
- source/commands/_commandDictionary.js
- source/commands/rank/index.js
- source/commands/seasonal-ranks.js
Summary
-------
- make  `/rank info` usable by all bounty hunters as `/seasonal-ranks`
Issue
-----
Closes #455
> #455: make  `/rank info` usable by all bounty hunters as `/seasonal-ranks`

- source/commands/raffle/byrank.js
Summary
-------
- fix `/raffle by-rank` replying to an ephemeral message
Issue
-----
Closes #418
> #418: fix `/raffle by-rank` replying to an ephemeral message

- ChangeLog.md
- source/commands/bounty/addcompleters.js
- source/commands/bounty/index.js
- source/commands/bounty/verify-turn-in.js
- source/logic/bounties.js
Summary
-------
- switch `/bounty add-completers` option from String to User
- rename command to `bounty verify-turn-in`
Issue
-----
Closes #466
> #466: switch `/bounty add-completers` option from String to User

- source/commands/toast.js
- source/context_menus/Raise_a_Toast.js
- source/models/toasts/Toast.js
Summary
-------
- `/toast` filters out duplicate toastees
- `/toast` provides a followup on successful toasts if any toastees were banned
> avoid duplicating toastees

- source/bot.js
- source/buttons/secondtoast.js
- source/commands/bounty/index.js
- source/commands/moderation/bountybotban.js
- source/commands/toast.js
- source/context_menus/Raise_a_Toast.js
Summary
-------
- consolidate BountyBot banned check to interactionCreate listener
> consolidate BountyBot banned check to interactionCreate listener

- ChangeLog.md
- source/commands/bounty/complete.js
Summary
-------
- switch `/bounty complete` option from String to User
- refactor initial member collection to use Collection instead of two Arrays
- Collection uses Map's key-based `.has()`, so it should be as performant as an Array and a Set
Issue
-----
Closes #467
> #467: switch `/bounty complete` hunter options from String to User

- ChangeLog.md
- source/commands/evergreen/complete.js
- source/util/textUtil.js
Summary
-------
- switch `/evergreen complete` `hunters` option from String to User
- remove deduplication from hunter list to allow awarding for multiple turn-ins in same command
Issue
-----
Closes #469
> #469: switch `/evergreen complete` hunter options from String to User

- ChangeLog.md
- source/commands/bounty/index.js
- source/commands/bounty/removecompleters.js
- source/commands/bounty/revoke-turn-in.js
- source/commands/toast.js
- source/models/bounties/Bounty.js
Summary
-------
- switch `/bounty remove-completers` option from String to User
- reduce wordiness in `/toast` option descriptions
- rename to `/bounty revoke-turn-in`
Issue
-----
Closes #468
> #468: switch `/bounty remove-completers` hunter options from String to User

- ChangeLog.md
- source/frontend/commands/bounty/verify-turn-in.js
- source/frontend/shared/dAPIRequests.js
- source/logic/bounties.js
Summary
-------
- change input method for `/bounty verify-turn-in` to in-message selects
- fix vestigial `this` in `updatePosting`
- combine `updatePosting` functions in shared and `verify-turn-in`
Issue
-----
Closes #483
> #483: change input method for `/bounty verify-turn-in` to in-message selects

- source/frontend/buttons/bbcomplete.js
- source/frontend/commands/bounty/complete.js
- source/frontend/shared/index.js
- source/frontend/shared/messageParts.js
- source/frontend/shared/storeManagement.js
- source/logic/bounties.js
- source/logic/hunters.js
Summary
-------
- accept company and season as parameters
- move reward text generation to frontend
- create `frontend/shared/storeManagement.reloadHunterMapSubset()` for reloading select Hunter objects in a `Record<hunter userId, Hunter>` object (the upcoming advised data structure for "all of a Company's Hunters" for the purpose of rank calculation)
> refactor `logicLayer.bounties.completeBounty()`

- ChangeLog.md
- source/frontend/buttons/secondtoast.js
- source/frontend/commands/bounty/complete.js
- source/frontend/commands/evergreen/complete.js
- source/frontend/commands/toast.js
- source/frontend/context_menus/Raise_a_Toast.js
- source/frontend/shared/dAPIRequests.js
- source/logic/bounties.js
Summary
-------
- switch `/evergreen complete` input to in-message selects
- fix crash when `/evergreen complete` creates Completion for not yet existing Hunter
- fix banned hunters being able to be credited with evergreen bounties
- move raw completion mapping into `bulkCreateCompletion()`
- create dAPI request `sendToRewardThread()`
Issue
-----
Closes #492, Closes #493
> #492 & #493: switch `/evergreen complete` input to in-message selects

- ChangeLog.md
- source/frontend/buttons/bbcomplete.js
- source/frontend/buttons/bbtakedown.js
- source/frontend/commands/item.js
- source/frontend/commands/raffle/byrank.js
Summary
-------
This PR started by noticing the Bounty Board Complete Button was returning an unknown interaction error on its final interaction (`collectedInteraction`) acknowledgement. This error has been diagnosed to be due to interaction timeouts for the following reasons:
- The code is only capable of acknowledging `collectedInteraction` once
- Bounty completions have had history of timing out
- The circumstance of "happens more often on first command after a period of inactivity" fits with "server setting of anaemic slows down first responses after inactivity, but saves on resources overall"
Analytical code inspection discovered that the Bounty Board Complete Button's `deferReply()` was being applied to the initial interaction (`interaction`) rather than the one that was throwing …
> maintenance pass on `deferReply()` usages

- package-lock.json
- package.json
Summary
-------
- update `sequelize-cli` to v6.6.3
Issue
-----
Closes #505
> #505: update `sequelize-cli` to v6.6.3

- package-lock.json
- package.json
Summary
-------
- update `@sapphire/discord.js-utilities` to v7.3.3
Issue
-----
Closes #506
> #506: update `@sapphire/discord.js-utilities` to v7.3.3

- package-lock.json
- package.json
Summary
-------
- update to Discord.js v14.20.0
- resolves vulnerability, stay up to date
> update Discord.js to v14.20.0

- package-lock.json
- package.json
Summary
-------
- update discord.js to v14.21.0
> update discord.js to v14.21.0

- migrations/20250626235952-addCustomizableRaffleThumbnail.js
- source/database/models/companies/Company.js
- source/frontend/commands/config-premium.js
- source/frontend/commands/raffle/by-level.js
- source/frontend/commands/raffle/by-rank.js
- source/frontend/shared/messageParts.js
- source/logic/companies.js
- source/logic/hunters.js
Summary
-------
- improve reply messages for raffles
After trying out containers for the reply messages, embeds looked better and had more formatting capabilities for text. Sending a "is typing" indicator was deemed to be gimmicky and breaking of UX convention.
Issue
-----
Closes #439
> #439: improve reply messages for raffles

- source/frontend/commands/bounty/swap.js
- source/logic/bounties.js
Summary
-------
Some of the functions being moved or replicated in #419 are old enough to benefit from being refactored. I'm going to split the actual refactors out to separate PRs so that #419's PR can be mostly structural.
Here are the changes for `/bounty swap`:
- add validation for source bounty being completed before slot is selected
- expand destination bounty validation to include destination bounty being completed before slot is selected
- reduce duplicate fetches (allowing the deprecation of `logicLayer.bounties.bulkFindOpenBounties()`)
- switch to `Model.update()` over set and save
- use formating function instead of literal markdown
- avoid recalculating poster level for each bounty when generating slot options
> `/bounty swap` improvements
